global:
  scrape_interval: 15s
# Prometheus v2.51+ supports native OTLP/HTTP receiver when started with --web.enable-otlp-receiver
# Alloy will send metrics via OTLP HTTP to /api/v1/otlp
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'oneservice-agents'
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/*.json
        refresh_interval: 30s
