global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'oneservice-agents'
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/*.json
        refresh_interval: 30s
