services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: oneservice
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/10-init.sql:ro

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio:/data

  minio-setup:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_started
    entrypoint: ["/bin/sh", "-c"]
    command: >
      i=0; until mc alias set local http://minio:9000 minio minio123; do i=$$((i+1)); echo "waiting for minio... $$i"; sleep 2; done &&
      mc mb -p local/thanos || true &&
      mc mb -p local/artifacts || true &&
      mc mb -p local/tempo || true

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]
    ulimits:
      memlock:
        soft: -1
        hard: -1

  grafana:
    image: grafana/grafana:10.2.3
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    ports: ["3000:3000"]
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on: [prometheus, tempo, loki]

  prometheus:
    image: prom/prometheus:v2.51.2
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--enable-feature=otlp-write-receiver"
    ]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - promdata:/prometheus
      - promfilesd:/etc/prometheus/file_sd
    ports: ["9090:9090"]

  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.34.0
    command: sidecar --tsdb.path=/prometheus --prometheus.url=http://prometheus:9090 --objstore.config-file=/etc/thanos/objstore.yml
    volumes:
      - promdata:/prometheus
      - ./thanos/objstore.yml:/etc/thanos/objstore.yml
    depends_on: [prometheus, minio]

  thanos-query:
    image: quay.io/thanos/thanos:v0.34.0
    command: query --http-address=0.0.0.0:10902 --store=thanos-sidecar:10901
    ports: ["10902:10902"]
    depends_on: [thanos-sidecar]

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector:0.104.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel/config.yaml:/etc/otelcol/config.yaml
    depends_on: [jaeger]

  oneservice-backend:
    build: ../backend
    environment:
      GRAFANA_URL: http://grafana:3000
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: artifacts
      NODE_EXPORTER_PORT: "9100"
    depends_on: [postgres, minio, opensearch, grafana, prometheus, thanos-query, jaeger, otel-collector]
    ports: ["8000:8000"]
    volumes:
      - promfilesd:/etc/prometheus/file_sd

  oneservice-frontend:
    build: ../frontend
    depends_on: [oneservice-backend, grafana]
    ports: ["8080:80"]
    environment:
      NODE_EXPORTER_PORT: "9100"

  mnist-test:
    platform: linux/arm64
    build:
      context: ../test
      dockerfile: backend/Dockerfile
    ports: ["8001:8001"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_SERVICE_NAME=mnist-test

  # Spring Boot OTEL demo that self-generates traffic
  spring-otel-demo:
    build:
      context: ../test2/spring-otel-demo
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=spring-otel-demo
      - SERVER_PORT=8088
    ports:
      - "8088:8088"
    depends_on: [alloy]

  # Grafana Alloy for OTLP reception and processing
  alloy:
    image: grafana/alloy:v1.5.0
    command: ["run", "/etc/alloy/config.alloy"]
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    depends_on: [prometheus, tempo, loki]

  # Grafana Tempo for traces (stores data in MinIO via S3 API)
  tempo:
    image: grafana/tempo:2.5.0
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempodata:/var/tempo
    ports:
      - "3200:3200"  # Tempo HTTP API / Grafana datasource
      - "14268:14268" # Jaeger ingest (optional)
    depends_on:
      minio-setup:
        condition: service_completed_successfully

  # Grafana Loki for logs
  loki:
    image: grafana/loki:3.1.1
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - lokidata:/loki
    ports:
      - "3100:3100"


volumes:
  pgdata:
  minio:
  promdata:
  promfilesd:
  lokidata:
  tempodata:
